FROM openjdk:22-oracle

# Set the working directory inside the container
WORKDIR /app

# Copy the JAR file into the container
COPY AMS.jar /app/AMS.jar

# Specify the command to run the JAR file
CMD ["java", "-jar", "AMS.jar"]
